### ISSUE TITLE
Error while Uploading Model Explainations using Azure-Interpret ExplanationClient

### ISSUE THREAD

**Issue by demihuman2020** [interpretml/interpret-community#293]
Our model is RandomForestRegressor from sklearn.ensemble.

```
import lightgbm
from interpret.ext.blackbox import PFIExplainer
#from interpret.ext.glassbox import DecisionTreeExplainableModel
from azureml.contrib.interpret.explanation.explanation_client import ExplanationClient
model = train_model(X_train_df,y_train_df)

explainer = PFIExplainer(model, features = feature_names)

global_explanation = explainer.explain_global(X_test_df[0:50],true_labels=y_test_df[0:50])

explain_client = ExplanationClient.from_run(run)
explain_client.upload_model_explanation(global_explanation)
```
We are getting the following error

```
Traceback (most recent call last):
  File "training/train.py", line 83, in <module>
    explain_client.upload_model_explanation(global_explanation)
  File "/azureml-envs/azureml_d5d57a45ca9af991b8408524822c201f/lib/python3.6/site-packages/azureml/interpret/_internal/explanation_client.py", line 793, in upload_model_explanation
    asset_type=History.ASSET_TYPE
TypeError: create_asset() got an unexpected keyword argument 'asset_type'
```
We have tried - TabularExplainer, MimicExplainer(with DecisionTreeExplainableModel) but all of them result in the same error.

**Comment by imatiach-msft** [comment]
hi @demihuman2020 , this is actually a problem in the explanation client which is azure specific (interpret-community is an open source package which doesn't have any azure-specific logic or integration in it).  I think in the future a better place to post questions about explanation client would be in:
https://github.com/Azure/MachineLearningNotebooks

However, having said this, I've seen this issue before and it is due to an older version of azureml-sdk (specifically azureml-core) use with a newer version of azureml-interpret.  I would recommend upgrading the azureml-sdk with:
```
pip install --upgrade azureml-sdk[automl,explain]
```
Please let me know if you are still seeing the issue.  Also, please post the package versions you currently have with:
```
pip freeze
```
hope this resolves your issue.

**Comment by vinpalapact** [comment]
Hi @imatiach-msft Thanks for the response..pip list gives the following -

azure-core                           1.7.0
azure-graphrbac                      0.61.1
azure-identity                       1.2.0
azure-mgmt-authorization             0.60.0
azure-mgmt-containerregistry         2.8.0
azure-mgmt-keyvault                  2.2.0
azure-mgmt-resource                  10.1.0
azure-mgmt-storage                   11.1.0
azure-storage-blob                   12.3.1
azureml-automl-core                  1.10.0.post1
azureml-automl-runtime               1.10.0.post1
azureml-contrib-notebook             1.10.0
azureml-core                         1.10.0.post1
azureml-dataprep                     1.10.1
azureml-dataprep-native              14.2.1
azureml-dataset-runtime              1.10.0
azureml-defaults                     1.10.0
azureml-explain-model                1.10.0
azureml-interpret                    1.10.0
azureml-model-management-sdk         1.0.1b6.post1
azureml-pipeline                     1.10.0
azureml-pipeline-core                1.10.0
azureml-pipeline-steps               1.10.0
azureml-sdk                          1.10.0
azureml-telemetry                    1.10.0
azureml-train                        1.10.0
azureml-train-automl                 1.10.0
azureml-train-automl-client          1.10.0
azureml-train-automl-runtime         1.10.0
azureml-train-core                   1.10.0
azureml-train-restclients-hyperdrive 1.5.0
azureml-widgets                      1.10.0
msrestazure                          0.6.4

**Comment by imatiach-msft** [comment]
@vinpalapact  hmm this all looks fine, I'm not sure what is causing the issue.  I can try to reproduce it locally.  How can I create X_train_df, y_train_df from the code above?  Can I access that dataset?

**Comment by gaugup** [comment]
@demihuman2020 are you still blocked on this or are you able to make progress?

**Comment by gaugup** [comment]
@demihuman2020 closing this issue since there is no activity on the thread for sometime now. For azureml related issue, please bring them up on some internal Microsoft alias. 

Regards
