### ISSUE TITLE
The number of feature names is not right when use 'LinearExplainableModel' for MimicExplainer

### ISSUE THREAD

**Issue by PengSY** [interpretml/interpret-community#337]
We are using `MimicExplainer` with `LinearExplainableModel`. And we got this error when the model task is classification, but if we change to use `LGBMNExplainableModel`, no error occurred.
```
Traceback (most recent call last):
  File "E:/scripts/interpret_debug.py", line 44, in <module>
    explanation = explainer.explain_global(evaluation_examples=data_x)
  File "E:\anaconda3\envs\ModuleX\lib\site-packages\interpret_community\mimic\mimic_explainer.py", line 413, in explain_global
    return _aggregate_global_from_local_explanation(**kwargs)
  File "E:\anaconda3\envs\ModuleX\lib\site-packages\interpret_community\explanation\explanation.py", line 1543, in _aggregate_global_from_local_explanation
    kwargs = _get_aggregate_kwargs(local_explanation, include_local, features, explanation_id, **kwargs)
  File "E:\anaconda3\envs\ModuleX\lib\site-packages\interpret_community\explanation\explanation.py", line 1491, in _get_aggregate_kwargs
    kwargs[ExplainParams.NUM_FEATURES] = local_explanation.num_features
  File "E:\anaconda3\envs\ModuleX\lib\site-packages\interpret_community\explanation\explanation.py", line 276, in num_features
    raise Exception('The number of feature names passed in must be the same as the number of '
Exception: The number of feature names passed in must be the same as the number of columns in the data.
```
After some debugging, it looks like the `kwargs[ExplainParams.NUM_FEATURES]` is not set as expected if the `raw_importances` is a 1d list of sparse matrix in `explanation.py`:
https://github.com/interpretml/interpret-community/blob/cefb4555c4d3a074958a29494a43897226bc867c/python/interpret_community/explanation/explanation.py#L1576-L1584

And this error can be reproduced by the following codes:
```
import scipy
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LogisticRegression
from interpret_community.mimic.models.linear_model import LinearExplainableModel
from interpret_community.mimic.mimic_explainer import MimicExplainer
from interpret_community.common.constants import ModelTask
from interpret_community.mimic.models.lightgbm_model import LGBMExplainableModel

# prepare sample dataset
n_samples = 100
n_cat_features = 15

cat_feature_names = [f'cat_feature_{i}' for i in range(n_cat_features)]
cat_features = np.random.choice(['a', 'b', 'c', 'd'], (n_samples, n_cat_features))

data_x = pd.DataFrame(cat_features, columns=cat_feature_names)
data_y = np.random.choice(['0', '1'], n_samples)

# prepare feature encoders
cat_feature_encoders = [OneHotEncoder().fit(cat_features[:, i].reshape(-1, 1)) for i in range(n_cat_features)]

# fit binary classification model
encoded_cat_features = [cat_feature_encoders[i].transform(cat_features[:, i].reshape(-1, 1)) for i in
                        range(n_cat_features)]
encoded_cat_features = scipy.sparse.hstack(encoded_cat_features, format='csr')

model = LogisticRegression(random_state=42).fit(encoded_cat_features, data_y)

# generate explanation
cat_transformations = [([cat_feature_name], encoder) for cat_feature_name, encoder in
                       zip(cat_feature_names, cat_feature_encoders)]

explainer = MimicExplainer(model=model,
                           initialization_examples=data_x,
                           explainable_model=LinearExplainableModel,  # if use 'LGBMExplainableModel', no error raised
                           explainable_model_args={'sparse_data': True},
                           augment_data=False,
                           features=cat_feature_names,
                           classes=['0', '1'],
                           transformations=cat_transformations,
                           model_task=ModelTask.Classification)
explanation = explainer.explain_global(evaluation_examples=data_x)
```

**Comment by gaugup** [comment]
Hi PengSY,

Thanks for reporting this issue. I have created a PR https://github.com/interpretml/interpret-community/pull/343 to fix this issue. 

Regards,
Gaurav
